apiVersion: operator.etcd.io/v1alpha1
kind: EtcdCluster
metadata:
  labels:
    app.kubernetes.io/name: etcd-operator
    app.kubernetes.io/managed-by: kustomize
  name: etcdcluster-sample
spec:
  size: 3
  version: "v3.5.21"
  tls:
    provider: "cert-manager"
    providerCfg:
      certManagerCfg:
        commonName: "etcd.etcd-operator-system"
        organizations:
          - "etcd-operator"
        altNames:
          dnsNames:
            - "etcd.etcd-operator-system"
          ipAddresses:
            - 192.168.0.5
        issuerName: "selfsigned"
        issuerKind: "ClusterIssuer"
