apiVersion: operator.etcd.io/v1alpha1
kind: EtcdCluster
metadata:
  labels:
    app.kubernetes.io/name: etcd-operator
    app.kubernetes.io/managed-by: kustomize
  name: etcdcluster-sample
spec:
  # TODO(user): Add fields here
  size: 4
  version: "3.5.17"
  tls:
    member:
      peerSecret: etcd-peer-tls
      serverSecret: etcd-server-tls
    operatorSecret: etcd-client-tls
    provider: cert-manager

